(* generated by tools/gen_domsep.py -- single source wolfssl/wolfcrypt/mask_prf.h *)
op domsep_RNDIMSK_ = 0x524E44494D534B5F.
op domsep_QUPNMSK_ = 0x5155504E4D534B5F.
op domsep_ESPSNW__ = 0x455350534E575F5F.
op domsep_OSCORE__ = 0x4F53434F52455F5F.
op mask_prf_domsep_table = [0x524E44494D534B5F; 0x5155504E4D534B5F; 0x455350534E575F5F; 0x4F53434F52455F5F].
