(* generated by tools/gen_domsep.py -- single source wolfssl/wolfcrypt/mask_prf.h *)
From Stdlib Require Import List NArith.
Import ListNotations.
Definition domsep_RNDIMSK_ : N := 0x524E44494D534B5F%N.
Definition domsep_QUPNMSK_ : N := 0x5155504E4D534B5F%N.
Definition domsep_ESPSNW__ : N := 0x455350534E575F5F%N.
Definition domsep_OSCORE__ : N := 0x4F53434F52455F5F%N.
Definition mask_prf_domsep_table : list N := [0x524E44494D534B5F%N; 0x5155504E4D534B5F%N; 0x455350534E575F5F%N; 0x4F53434F52455F5F%N].
