#!/usr/bin/env python3
"""gen_domsep — single source domsep table -> formal artifacts (mask_prf.h)"""
import pathlib
tbl=[("RNDIMSK_",0x524E44494D534B5F),("QUPNMSK_",0x5155504E4D534B5F),("ESPSNW__",0x455350534E575F5F),("OSCORE__",0x4F53434F52455F5F)]
root=pathlib.Path(__file__).resolve().parents[1]
coq=root/"formal/coq/mask_prf_domsep.v"
ec=root/"formal/easycrypt/mask_prf_domsep.ec"
coq.parent.mkdir(parents=True,exist_ok=True)
ec.parent.mkdir(parents=True,exist_ok=True)
hexs=[f"0x{v:016X}" for _,v in tbl]
coq.write_text("(* generated by tools/gen_domsep.py -- single source wolfssl/wolfcrypt/mask_prf.h *)\nFrom Stdlib Require Import List NArith.\nImport ListNotations.\n"+"\n".join([f"Definition domsep_{k} : N := {h}%N." for (k,_),h in zip(tbl,hexs)])+"\nDefinition mask_prf_domsep_table : list N := ["+"; ".join([h+"%N" for h in hexs])+"].\n")
ec.write_text("(* generated by tools/gen_domsep.py -- single source wolfssl/wolfcrypt/mask_prf.h *)\nrequire import AllCore List.\n"+"\n".join([f"op domsep_{k} = {h}." for (k,_),h in zip(tbl,hexs)])+"\n"+"op mask_prf_domsep_table = [0x524E44494D534B5F; 0x5155504E4D534B5F; 0x455350534E575F5F; 0x4F53434F52455F5F].\n")
print(f"wrote {coq} and {ec}")
